contact_links:
  - name: Discord
    url: https://discord.gg/FnGFbzCw2r
    about: The Tixte4J Discord is the best place to receive fast support for your questions.
  - name: Releases
    url: https://github.com/BlockyDotJar/Tixte-Java-Library/releases
    about: You can find the latest releases here on GitHub.
  - name: Questions
    url: https://github.com/BlockyDotJar/Tixte-Java-Library/discussions
    about: You can ask questions about Tixte4J and find useful information in our discussions.